### ISSUE TITLE
same error again 

### ISSUE THREAD

**Issue by cjf9028** [bamtercelboo/PyTorch_Biaffine_Dependency_Parsing#2]
/pytorch/aten/src/THC/THCTensorIndex.cu:308: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:308: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:308: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    main()
  File "main.py", line 95, in main
    start_train(train_iter, dev_iter, test_iter, parser, config)
  File "main.py", line 43, in start_train
    t.train()
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/trainer.py", line 190, in train
    self.eval(parser=self.parser, epoch=epoch, config=self.config)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/trainer.py", line 202, in eval
    self._eval_batch(self.dev_iter, parser, self.best_score, epoch, config, test=False)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/trainer.py", line 248, in _eval_batch
    arcs_batch, rels_batch = parser.parse(words, ext_words, tags, lengths, masks)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Parser.py", line 117, in parse
    self.forward(words, extwords, tags, masks)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Parser.py", line 43, in forward
    arc_logits, rel_logits = self.model.forward(words, ext_words, tags, masks)
  File "/home/nlplab/Development/ckc/parsing/PyTorch_Biaffine_Dependency_Parsing/Model/Biaffine_Parsing/Model.py", line 97, in forward
    x_embed = x_word_embed + x_ext_word_embed
RuntimeError: CUDA error: device-side assert triggered

now i add in run_train_p.sh
export CUDA_LAUNCH_BLOCKING=1

and my dataset 50000/1000/1000

this error happen after 1 epoch train 

error first part like this 
Train Time 417.859/pytorch/aten/src/THC/THCTensorIndex.cu:308: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by bamtercelboo** [comment]
it happens after one epoch train, this so strange.

last time, can you run many epoch ?

**Comment by cjf9028** [comment]
in last issues i run 10 epoch 
this error not happend 
so i ran 100 epoch and sleep 
but this error happend first epoch after train part

**Comment by bamtercelboo** [comment]
I think this error also associates with cuda, but I can not solve it quickly.

**Comment by bamtercelboo** [comment]
pytorch and cuda version is same as my requirement?

**Comment by cjf9028** [comment]
cuda 9.0 
totch 1.0.0
python 3.7 
i will change python version

**Comment by cjf9028** [comment]
train_file = ./Data/ctb51/dev.conll
dev_file = ./Data/ctb51/dev.conll
test_file = ./Data/ctb51/test.conll

in this 
error happend after dev

**Comment by bamtercelboo** [comment]
I run it ok, not ensure why happens the problem?

**Comment by bamtercelboo** [comment]
Have you solved the problem yet？

**Comment by cjf9028** [comment]
now has same error 
maybe embedding problem
